sudo: required
services:
  - docker

before_install:
  - docker build -t imrancluster/docker-react -f Dockerfile.dev .

install: travis_wait 30 mvn install

script:
  - docker run imrancluster/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"